version: "3"

services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    environment:
      - FLASK_APP=server.py
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    command: ["gunicorn", "server:app", "-c", "./gunicorn.conf.py"]
    ports:
      - "8000:8000"